# Site settings
title: Jared Rewerts
email: jaredrewerts@gmail.com
url: https://j-rewerts.github.io
description: "Looking for a full stack engineer with a dedication to providing value? Come check out some of my projects!"
keywords: "fullstack, engineer, javascript, css, html, containerization, scalability, software engineer"
skills: "Web App Developer - Full-stack Engineer - MongoDB Wizard"
meta_author: Rewerts Jared

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/jared-rewerts
  - title: stack-overflow
    url: https://stackoverflow.com/users/6710784/jared-rewerts
  - title: github
    url: https://github.com/j-rewerts

# Postal address (add as many lines as necessary)
address:
  - line: Edmonton AB,  T5H 3S4

# Build settings
markdown: kramdown
permalink: pretty
