# Site settings
title: J / R
email: jaredrewerts@gmail.com
url: https://j-rewerts.github.io
description: "Looking for a full stack engineer with a dedication to providing value? Come check out some of my projects!"
keywords: "fullstack, engineer, javascript, css, html, containerization, scalability, software engineer"
skills: "beautiful experiences at scale"
meta_author: Rewerts Jared

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 333 #80B3FF
  primary-rgb: "51, 51, 51" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jared Rewerts
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/jared-rewerts
  - title: stack-overflow
    url: https://stackoverflow.com/users/6710784/jared-rewerts
  - title: github
    url: https://github.com/j-rewerts

# Postal address (add as many lines as necessary)
address:
  - line: Edmonton AB,  T5H 3S4

# Build settings
markdown: kramdown
permalink: pretty

# Skills that show up on the about page.
about:
  techSkills:
    - name: CSS
      value: 60%
    - name: HTML
      value: 90%
    - name: JS
      value: 80%
    - name: K8s
      value: 40%
    - name: Docker
      value: 60%
    - name: Node.js
      value: 60%
    - name: C#
      value: 50%
    - name: Mongo DB
      value: 70%
    - name: SQL
      value: 50%
